# Site settings
title: Yewon Lim
description: Resume and tech blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://three0-s.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yewon Lim
user_description: I'm a student major in Mechanical Engineering in Yonsei Univ., Seoul. I'm into Machine Learning, especially applying ML techinques into the robotics. Recently I am studying 'Pattern Recognition and Machine Learning', posting examples of this book on my blog and github. You can find the links at the bottom of this site. I'm comfortable with various programming languages including Python3, C and C++. I am used to Numpy, Pandas, Keras, Scikit-learn and STL. I don't have much experience in practical Machine Learning projects, but I am surely prepared for the ones. I'm familiar with Probabilistics, Linear Algebra, and Calculus.
user_title: Bachelor Student
email: ga06033@yonsei.ac.kr
# twitter_username: lorem_ipsum
github_username:  three0-s
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
